# Generated by Django 5.0.2 on 2024-02-09 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('cui', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='MedicalApointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('reason', models.CharField(max_length=200)),
                ('observations', models.TextField()),
                ('prescription', models.TextField()),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Atendido', 'Atendido')], default='Pendiente', max_length=20)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.RemoveConstraint(
            model_name='paciente',
            name='unique_cui_name',
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('cui', 'name'), name='unique_cui_name_patient'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(fields=('cui', 'name'), name='unique_cui_name_doctor'),
        ),
        migrations.AddField(
            model_name='medicalapointment',
            name='cui',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Paciente.paciente'),
        ),
        migrations.AddField(
            model_name='medicalapointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Paciente.doctor'),
        ),
        migrations.AddConstraint(
            model_name='medicalapointment',
            constraint=models.UniqueConstraint(fields=('cui', 'doctor', 'date', 'hour'), name='unique_cui_doctor_date_hour'),
        ),
    ]
