version: "2.2"

services:
  db:
    ports:
      - 5432:5432
    image: postgres:13
    volumes:
      - projectdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DBUSER=postgres
      - DBPASSWORD=postgres
  web:
    build: .
    # command: gunicorn authapp.wsgi -b 0.0.0.0:8000 --workers 3 --threads=3  
    command: python /code/manage.py runserver 0.0.0.0:8000
  
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    image: nginx:1.19.0
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/demu/BasicDjangoProject/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/html:/var/www/html
    restart: always
    depends_on:
      - web
               
   
volumes:
  projectdb:
