version: "2.2"

services:
  db:
    ports:
      - 5432:5432
    image: postgres:13
    volumes:
      - projectdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - DBUSER=postgres
      - DBPASSWORD=postgres
  web:
    build: .
    # command: gunicorn authapp.wsgi -b 0.0.0.0:8000 --workers 3 --threads=3  
    command: python /code/manage.py runserver 0.0.0.0:8000
  
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - /var/www/html:/var/www/html
    depends_on:
      - web
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
               
   
volumes:
  projectdb: